name: Stock Monitor

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 確保有寫入權限
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run script
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
          # 僅當檔案存在且有變更時才執行 Git 指令
          if [ -f "inventory_report.csv" ]; then
            git add inventory_report.csv
            if ! git diff --quiet --staged; then
              git commit -m "Update inventory report - $(date '+%Y-%m-%d %H:%M:%S')"
              git push
            else
              echo "無數據變更，跳過提交。"
            fi
          else
            echo "檔案尚未產生，跳過提交。"
          fi
